quiz/config/routes.rb
Rails.application.routes.draw do
  resources :questions

  root 'questions#index'
end

quiz/app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessor :question, :answer, :one, :two, :three, :four
end

quiz/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :email, :password
end

quiz/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

quiz/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new()
  end

  def create
    @question = Question.new(question_params) #.permit(:question, :answer, :one, :two, :three, :four)

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  private
    def question_params
      params.require(:question).permit(:question,:answer, :one, :two, :three, :four)
    end

end

quiz/app/helpers/application_helper.rb
module ApplicationHelper
end

quiz/app/helpers/questions_helper.rb
module QuestionsHelper
end

quiz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

quiz/app/views/questions/index.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<h1><%= link_to 'All Questions', controller: 'questions' %></h1>

<% @questions.each do |question| %>
<div>
  <div class="question-question">
    <h3><%= question.question %></h3>
  </div>
  <div class="question-one">
  <%= question.one %>
  </div>
  <div class="question-two">
  <%= question.two %>
  </div>
  <div class="question-three">
  <%= question.three %>
  </div>
  <div class="question-four">
  <%= question.four %>
  </div>
</div>
<% end %>
<br>
<div class="new-question">
  <%= link_to 'New Question', new_question_path, {class: 'allquestions-link'} %>
</div>

quiz/app/views/questions/new.html.erb
<h1>New Question</h1>
<%= form_for(@question) do |f| %>
  <p>
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </p>

  <p>
    <%= f.label :one %><br>
    <%= f.text_area :one %>
  </p>

  <p>
    <%= f.label :two %><br>
    <%= f.text_area :two %>
  </p>

  <p>
    <%= f.label :three %><br>
    <%= f.text_area :three %>
  </p>

  <p>
    <%= f.label :four %><br>
    <%= f.text_area :four %>
  </p>

  <p>
    <%= f.label :answer %><br>
    <%= f.text_area :answer %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

quiz/app/views/questions/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @question.question %>
</p>